wget -q www.cs.uakron.edu/~toneil/teaching/cs426/blackdos/lab04%20load%20exec%20progs/blackdos.asm && echo "Downloaded blackdos.asm"
wget -q www.cs.uakron.edu/~toneil/teaching/cs426/blackdos/lab04%20load%20exec%20progs/blackdos.h && echo "Downloaded blackdos.h"
wget -q www.cs.uakron.edu/~toneil/teaching/cs426/blackdos/lab04%20load%20exec%20progs/fib.c && echo "Downloaded fib.c"
wget -q www.cs.uakron.edu/~toneil/teaching/cs426/blackdos/lab04%20load%20exec%20progs/kitty1 && echo "Downloaded kitty1"
wget -q www.cs.uakron.edu/~toneil/teaching/cs426/blackdos/lab04%20load%20exec%20progs/kitty2 && echo "Downloaded kitty2"
wget -q www.cs.uakron.edu/~toneil/teaching/cs426/blackdos/lab04%20load%20exec%20progs/Stenv && echo "Downloaded Stenv"
